### PR TITLE
Issue-8: Allows labeling context blocks

### PR DESCRIPTION
**Pull request by ErikDahlinghaus**
Updates documentation

See https://github.com/prashanth-sams/testrail-rspec/issues/8 for more details.

### CODE REVIEW

**Comment by prashanth-sams** [comment]
@ErikDahlinghaus Thank you for the PR 👍

**Comment by prashanth-sams** [comment]
@ErikDahlinghaus Added tests with few bug fixes. Thanks a bunch ;) will release these changes in version `0.1.5`

**Review by prashanth-sams — APPROVED** [review]
👍

**Comment by ErikDahlinghaus** [comment]
Thank you!

**Pull request merged**
